# Generated by Django 5.1.4 on 2024-12-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyreading',
            name='end_interval',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlyreading',
            name='start_interval',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hourlyreading',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
